Gem Devise
AShalysh/testguru pull request #11
Opened 2018-11-26 06:31 UTC by AShalysh

2018-11-26 15:21 UTC, iBublik requested changes

2018-11-26 15:21 UTC, iBublik commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized to view this page.' unless current_user.is_a?(Admin)
Проверку на админство лучше вынести в метод модели - она часто понадобится

2018-11-26 15:21 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +  def start
Этот экшн в контроллере админов не нужен

2018-11-26 15:21 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :user_id)
Связь с пользователем происходит не через параметры, а через ассоциации

2018-11-26 15:21 UTC, iBublik commented on app/controllers/application_controller.rb
> +    if resource.admin?
Не используй абстрактный нейминг там, где можно быть более конкретным. Ресурсом для аутентификации у нас будет только пользователь. Для простоты откажись от более общего `resource` в пользу `user`

2018-11-26 15:21 UTC, iBublik commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized to view this page.' unless current_user.is_a?(Admin)
А он уже есть, надо его только использовать

2018-11-26 15:21 UTC, iBublik commented on app/controllers/application_controller.rb
> +  # before_action :authenticate_user! #checking if user was auth
Ни к чему все эти комментарии хранить в репозитории. Git хранит историю, всегда можно откатиться назад и посмотреть что и как было реализовано раньше

2018-11-26 15:21 UTC, iBublik commented on app/models/admin.rb
> +  validates :last_name, presence: true
Можно описывать валидации нескольких полей разом - `validates :first_name, :last_name, presence: true`

2018-11-26 15:21 UTC, iBublik commented on app/models/user.rb
>    validates :email, format: { :with => /@/ },
Эти валидации уже не нужны, их делает девайс (опция validatable)

2018-11-26 15:21 UTC, iBublik commented on app/models/user.rb
> +    type == "Admin"
Лучше полагаться на класс, как ты сделала в контроллере. Если добавится подкласс Admin-а, который по сути тоже админ, эта проверка вернет false, а хотелось бы true (ведь подкласс админа тоже является админом)

2018-11-26 15:21 UTC, iBublik commented on routes.txt
> +                   Prefix Verb   URI Pattern                                                                              Controller#Action
Зачем это хранить в репозитории? Всегда можно получить через `rails routes`

2018-11-28 16:27 UTC, iBublik requested changes

2018-11-28 16:27 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> -  def test_params
А это зачем удалять? Теперь создание и редактирование тестов не работает

2018-11-28 16:27 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> -  def test_params
Связь с пользователем, который создал тест, вообще не устанавливается

2018-11-28 16:27 UTC, iBublik commented on app/controllers/my_devise/sessions_controller.rb
> +		set_flash_message :notice, :signed_in, user: current_user if is_navigational_format?
Что с отступами?

2018-11-28 16:27 UTC, iBublik commented on app/controllers/my_devise/sessions_controller.rb
> +class MyDevise::SessionsController < Devise::SessionsController
Можно просто `SessionsController` назвать, вряд ли будет 2 контроллера с таким именем в проекте

2018-11-28 16:27 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +    content_tag :p, flash[key] if key
1. Нужно, чтоб у разных типов флешей была разная стилизация. Для этого ты в css описала разные классы, используй их (от ключа зависит css класс)
2. Нужно проверять, что существует флеш с переданным ключом. `if key` бесполезная проверка, ведь ты передаешь строку или символ в качестве key, а они всегда эквивалентны `true`

2018-11-28 16:27 UTC, iBublik commented on app/models/admin.rb
> +  def admin?
Не нужно этот метод переопределять, достаточно правильно описать метод в User

2018-11-28 16:27 UTC, iBublik commented on app/models/user.rb
> +    type == "Admin"
`is_a?(Admin)` решает задачу идеально

2018-11-28 16:27 UTC, iBublik commented on config/locales/devise.en.yml
> +      signed_in: "Hi %{user.first_name}! You signed in successfully."
В yaml не работает исполнение кода. Сюда можно только передавать готовые строки, а YAML уже подставит их

2018-12-03 05:53 UTC, iBublik requested changes

2018-12-03 05:53 UTC, iBublik commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :user_id)
Зачем здесь этот метод?

2018-12-03 05:53 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +    content_tag(:p, flash[key], {class: "flash #{key.to_s}"}) if flash[key].present?
Фигурные скобки можно опустить

2018-12-03 05:53 UTC, iBublik commented on app/controllers/admin/answers_controller.rb
> +    @answer = Answer.new(answer_params)
А где связь ответа с вопросом?

2018-12-03 05:53 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
Метода test_params по-прежнему не существует

2018-12-03 05:53 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +    @test.author = current_user
Можно конечно так оставить, но лучше в модели пользователя добавить ассоциацию `own_tests`, и создавать тест через нее (`current_user.own_tests.build(...)`)

2018-12-03 05:53 UTC, iBublik commented on app/controllers/answers_controller.rb
>  class AnswersController < ApplicationController
Зачем этот контроллер нужен? Пользователю достаточно списка тестов и возможности их прохождения, остальные контроллеры и экшны ему недопступны

2018-12-03 05:53 UTC, iBublik commented on app/controllers/my_devise/sessions_controller.rb
> +    set_flash_message :notice, :signed_in, name: current_user.first_name if is_navigational_format?
1. Ты передаешь name в локаль, но там эту переменную никак не используешь
2. Ты используешь флеш devise-а, но он выводится только с помощью хелпера `devise_error_messages!`. Поэтому ты не видишь этот флеш. Либо воткни в шабон вызов этого хелпера, либо пиши в обычный флеш

2018-12-06 11:16 UTC, iBublik commented on app/controllers/admin/answers_controller.rb
> +  before_action :find_question, only: %i[new create index update edit destroy]
Зачем тебе вопрос в экшнах edit, update, destroy?

2018-12-06 11:16 UTC, iBublik commented on app/controllers/admin/answers_controller.rb
> +  def index
Список ответов можно было на странице вопроса выводить. Тогда не нужно отдельного экшна

2018-12-06 11:16 UTC, iBublik commented on app/controllers/admin/answers_controller.rb
> +    @answer.save!
Ты ниже делаешь сохранение, зачем еще тут? К тому же, если будет ошибка валидации, у тебя приложение упадет

2018-12-06 11:16 UTC, iBublik commented on app/controllers/admin/answers_controller.rb
> +      params.require(:answer).permit(:body, :correct, :question_id)
Зачем question_id в параметрах, если у тебя связь через ассоциации?

2018-12-06 11:16 UTC, iBublik commented on app/controllers/admin/questions_controller.rb
> +  before_action :find_test, only: [:index, :new, :create, :edit, :update]
Зачем тебе вопрос в экшнах edit, update?

2018-12-06 11:16 UTC, iBublik commented on app/controllers/admin/questions_controller.rb
>      @questions = @test.questions
Мы делали вывод вопросов на странице теста в предыдущих уроках, зачем отдельный экшн?

2018-12-06 11:16 UTC, iBublik commented on app/controllers/admin/questions_controller.rb
> +    if @question.update!(question_params)
Зачем ты заменила вызов на `update!`? Теперь условие не работает - при ошибках валидации приложение упадет

2018-12-06 11:16 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +    @test.save!
Зачем?

2018-12-06 11:16 UTC, iBublik commented on app/controllers/my_devise/sessions_controller.rb
> +  	super
Что с отступами?

2018-12-06 11:16 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +    content_tag(:p, flash[key], class: "flash #{key.to_s}") if flash[key].present?
Не надо ключ к строке приводить, интерполяция любой объект преобразует в строку

2018-12-06 11:16 UTC, iBublik commented on config/locales/devise.en.yml
> +      already_authenticated: "Hi %{name}! You are already signed in."
Зачем ты тут изменила? Девайс явно не передает никакого параметра в эту локаль, так что при ее вызове будет ошибка

2018-12-06 11:16 UTC, iBublik commented on config/routes.rb
> +    resources :questions do
Вложенность может иметь любой уровень:
```ruby
resources :tests do
  resources :questions do
    resources :answers
  end
end
```
И стоило указать опцию shallow: true для упрощения роутинга - http://rusrails.ru/rails-routing#melkoe-vlozhenie

2018-12-07 00:53 UTC, merged

2018-12-07 07:38 UTC, AShalysh commented on app/controllers/admin/answers_controller.rb
> +    @answer.save!
Toest', poskol'ky y nas est' stroka nomer 25, ja mogy 23 stroky ybrat'? verno?

2018-12-09 22:33 UTC, AShalysh commented on app/controllers/admin/answers_controller.rb
> +  def index
Ja ispol'zyu etot put', mne on bol'she nravitsia **/admin/questions/1/answers**
Pochemy hochesh' chtob ja etot' put' ispol'zovala?:
/admin/tests/1/questions/1

2018-12-10 07:39 UTC, AShalysh commented on config/routes.rb
> +    resources :questions do
То есть вот так будет правильно?
```
namespace :admin, shallow: true do
    resources :tests do
      resources :questions do
        resources :answers
      end
    end
  end
```

2018-12-10 07:53 UTC, iBublik commented on app/controllers/admin/answers_controller.rb
> +  def index
Я в целом не вижу особого смысла выводить список ответов на отдельной странице. `/admin/questions/1` - это show для вопроса, прямо там можно вывести все ответы на этот вопрос