Localized, changed the routes and made other small changes.
AShalysh/testguru pull request #12
Opened 2018-12-13 07:02 UTC by AShalysh

2018-12-13 16:43 UTC, iBublik requested changes

2018-12-13 16:43 UTC, iBublik commented on app/controllers/admin/answers_controller.rb
> +  # def index
Не надо комментировать - надо удалять

2018-12-13 16:43 UTC, iBublik commented on app/controllers/admin/questions_controller.rb
> +    #redirect_to admin_test_path(@test)
Теперь будет рендериться шаблон destroy, которого нет. 
Даже после удаления вопроса у нас есть доступ к его данным, в том числе к тесту. Потому что переменная находится в памяти

2018-12-13 16:43 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +      redirect_to [:admin, @test], notice: t('.success')
Придерживайся единообразия в коде - стоит использовать либо полную форму роут-хелперов (`admin_test_path`), либо сокращенную (`[:admin, @test]`)

2018-12-13 16:43 UTC, iBublik commented on app/controllers/application_controller.rb
> +    if I18n.locale == :ru
Надо не зашиваться на `:ru`, а смотреть на локаль по умолчанию

2018-12-13 16:43 UTC, iBublik commented on app/controllers/application_controller.rb
> +      { :locale => I18n.locale, lang: I18n.locale }
Зачем тебе 2 параметра?

2018-12-13 16:43 UTC, iBublik commented on app/controllers/application_controller.rb
> +      { :locale => nil }
Не используй старый формат записи хешей.
К тому же, из url-а выбрасываются параметры с nil-ом. Можно просто пустой хэш вернуть

2018-12-13 16:43 UTC, iBublik commented on app/controllers/my_devise/sessions_controller.rb
> +    set_flash_message :my_signed_in, :my_already_authenticated, name: current_user.first_name
1 параметром передается тип флеша, 2 - ключ. Вряд ли имеет смысл заводить тип отдельный флеша под эту задачу

2018-12-13 16:43 UTC, iBublik commented on app/models/category.rb
> +  def self.translated_collection
Что это?

2018-12-13 16:43 UTC, iBublik commented on app/models/category.rb
> +  def translated_category
?

2018-12-13 16:43 UTC, iBublik commented on app/models/question.rb
> +  has_many :test_passages, dependent: :destroy, foreign_key: :current_question
Что это?

2018-12-13 16:43 UTC, iBublik commented on app/controllers/my_devise/sessions_controller.rb
> +    set_flash_message :my_signed_in, :my_already_authenticated, name: current_user.first_name
И почему в качестве ключа my_already_authenticated тоже непонятно. С толку сбивает

2018-12-13 16:43 UTC, iBublik commented on app/views/admin/questions/_question.html.erb
> +    data: { confirm: t('.you_sure') } %> </td>
Такое стоит куда-то в shared помещать. Вряд ли будет изменяться в каждом шаблоне

2018-12-13 16:43 UTC, iBublik commented on app/views/admin/questions/_question.html.erb
> +  <td><%= link_to t('.show_question'), admin_question_path(question) %></td>
У тебя относительный путь. Он итак в себе содержит слово `question`, нет смысла это еще раз дублировать

2018-12-13 16:43 UTC, iBublik commented on app/views/test_passages/result.html.erb
> +  <p><%= t('.score-green', score: @test_passage.score) %></p>
Убери тогда строку выше. А то ведь одно и то же дважды выводится

2018-12-13 16:43 UTC, iBublik commented on config/locales/devise.en.yml
> +      my_already_authenticated: "Hi %{name}! You are already signed in."
Этот перевод никогда не будет использован

2018-12-14 06:46 UTC, AShalysh commented on app/controllers/application_controller.rb
> +      { :locale => I18n.locale, lang: I18n.locale }
lang: I18n.locale - этот параметр сохраняет один и тот же язык при переходе с одной странице на другую. Если его убрать язык прыгает. Остальная часть метода прячет в url дефолтный язык (en).  Я тоже думала как убрать этот второй параметр и куда, не знаю. Куда лучше его убрать?

2018-12-14 06:47 UTC, AShalysh commented on app/controllers/application_controller.rb
> +    if I18n.locale == :ru
Что это значит? по умолчанию у меня (en).

2018-12-14 07:11 UTC, AShalysh commented on app/models/question.rb
> +  has_many :test_passages, dependent: :destroy, foreign_key: :current_question
Я пыталась удалить вопрос, но не могла поскольку current_question_id сидел в test_passage table. пришлось это добавить

2018-12-14 07:57 UTC, AShalysh commented on config/locales/devise.en.yml
> +      my_already_authenticated: "Hi %{name}! You are already signed in."
да, а почему так происходит?

2018-12-17 15:51 UTC, iBublik commented on app/controllers/application_controller.rb
> +      { :locale => nil }
> Не используй старый формат записи хешей.
> К тому же, из url-а выбрасываются параметры с nil-ом. Можно просто пустой хэш вернуть

Актуально

2018-12-17 15:51 UTC, iBublik commented on app/views/shared/_delete_confirmation.html.erb
> +  <%= link_to t('.delete'),
Не нужно использовать относительные пути в shared паршлах - совершенно непонятно во что они разложатся.
Вообще я говорил про вынесенеие перевода в shared, чтоб во вьюхах было `t('shared.delete_confirmation')`. Паршл было создавать не обязательно, код только усложнился. Но можешь оставить, если тебя это не смущает

2018-12-17 15:51 UTC, iBublik commented on config/locales/devise.en.yml
> +      my_already_authenticated: "Hi %{name}! You are already signed in."
Потому что это кастомный ключ, который добавил ты. Соответственно использовать его можешь только ты, но в коде его нигде нет

2018-12-17 15:53 UTC, iBublik commented on app/models/category.rb
> +  def self.translated_collection
> Что это?

Актуально

2018-12-17 15:53 UTC, iBublik commented on app/models/category.rb
> +  def translated_category
?

2018-12-17 15:54 UTC, iBublik commented on app/models/question.rb
> +  has_many :test_passages, dependent: :destroy, foreign_key: :current_question
Ок, но у тебя ведь поле с внешним ключом не так называется. Как это работает?

2018-12-18 06:49 UTC, AShalysh commented on app/views/shared/_delete_confirmation.html.erb
> +  <%= link_to t('.delete'),
что такое относительный путь?

2018-12-18 06:52 UTC, AShalysh commented on app/views/shared/_delete_confirmation.html.erb
> +  <%= link_to t('.delete'),
тоесть мне надо было указать название папки.название_ключа

2018-12-18 06:54 UTC, AShalysh commented on app/views/shared/_delete_confirmation.html.erb
> +  <%= link_to t('.delete'),
думаю, оставлю без изменения, так удобнее мне

2018-12-18 07:18 UTC, AShalysh commented on app/models/question.rb
> +  has_many :test_passages, dependent: :destroy, foreign_key: :current_question
https://github.com/AShalysh/testguru/blob/master/app/models/test_passage.rb#L4

2018-12-18 15:35 UTC, iBublik approved these changes

2018-12-18 15:35 UTC, iBublik commented on app/controllers/application_controller.rb
> +      { lang: I18n.locale}
Поставь rubocop, повсюду ошибки форматирования в коде

2018-12-18 15:35 UTC, iBublik commented on app/models/question.rb
> +  has_many :test_passages, dependent: :destroy, foreign_key: :current_question
Внешний ключ - это _поле_ в таблице, в котором хранится связь.
По ссылке корректное описание связи - Rails вычисляют имя внешнего ключа из имени ассоциации (`current_question`), получается `current_question_id` - такое поле есть. 
Здесь же имя внешнего ключа вычисляется из имени модели, т.е. по умолчанию получается `question_id`. Такого поля нет, поэтому надо явно прописать его. Ты указываешь `current_question` - такого поля в таблице нет.
https://github.com/AShalysh/testguru/blob/4fa70e01cb9c61af2eca993e1f5dc35900efa2dc/db/schema.rb#L41

2018-12-18 15:35 UTC, iBublik commented on app/views/shared/_delete_confirmation.html.erb
> +  <%= link_to t('.delete'),
Это вообще никак не связано с именем папки. В shared обычно выносят универсальные локали, которые используются в разных местах приложения

2018-12-20 01:38 UTC, merged

2018-12-20 06:09 UTC, AShalysh commented on app/models/category.rb
> +  def translated_category
скорее всего что-то делала и забыла удалить)

2018-12-20 06:09 UTC, AShalysh commented on app/controllers/admin/answers_controller.rb
> +  # def index
убрала

2018-12-20 06:10 UTC, AShalysh commented on app/controllers/admin/questions_controller.rb
> +    #redirect_to admin_test_path(@test)
исправила

2018-12-20 06:11 UTC, AShalysh commented on app/controllers/admin/tests_controller.rb
> +      redirect_to [:admin, @test], notice: t('.success')
хорошо

2018-12-20 06:11 UTC, AShalysh commented on app/controllers/application_controller.rb
> +    if I18n.locale == :ru
переделала

2018-12-20 06:11 UTC, AShalysh commented on app/controllers/application_controller.rb
> +      { :locale => I18n.locale, lang: I18n.locale }
переделала

2018-12-20 06:50 UTC, AShalysh commented on config/locales/devise.en.yml
> +      my_already_authenticated: "Hi %{name}! You are already signed in."
исправила

2018-12-20 06:51 UTC, AShalysh commented on app/views/test_passages/result.html.erb
> +  <p><%= t('.score-green', score: @test_passage.score) %></p>
убрала

2018-12-20 06:53 UTC, AShalysh commented on app/models/category.rb
> +  def self.translated_collection
Удалила