API lesson
AShalysh/testguru pull request #14
Opened 2019-01-07 07:12 UTC by AShalysh

2019-01-08 08:46 UTC, iBublik requested changes

2019-01-08 08:46 UTC, iBublik commented on .env
> +GITHUB_TOKEN=b694fe861358948f2bf110ee7903bf6c282bb267
Этого не должно быть в репозитории. Скорее всего, токен уже отозван и не работает

2019-01-08 08:46 UTC, iBublik commented on app/controllers/admin/gists_controller.rb
> +  	@gists = Gist.all
Что с отступами?

2019-01-08 08:46 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +    Gist.create!(url: result.html_url, user: current_user, question: @test_passage.current_question)
А если сервис не создал гист (допустим произошла какая-то сетевая ошибка), зачем его сохранять в базу?

2019-01-08 08:46 UTC, iBublik commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
Никто в своем уме не будет передавать `nil` как 2й параметр. Поэтому здесь лучше писать так:
```ruby
def initialize(question, client: default_client)
  ...
  @client = client
end

private

def default_client
  Octokit::Client.new(...)
end
```

2019-01-08 08:46 UTC, iBublik commented on app/services/gist_question_service.rb
> +    @client = client || GitHubClient.new
По умолчанию нужно использовать официальный клиент гитхаба из гема octokit

2019-01-08 08:46 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +    flash_options = if result.url.present?
Выше html_url, тут url. Насколько помню, API возвращает только html_url

2019-01-08 08:46 UTC, iBublik commented on app/services/gist_question_service.rb
> +    content = [@question.body]
Можно посимпатичнее и покороче записать - `[@question.body, *@question.answers.pluck(:body)]`

2019-01-08 08:46 UTC, iBublik commented on app/views/admin/gists/_gist.html.erb
> +<% @gists.each do |gist| %>
По конвенции паршл `gist` рендерит строго 1 гист, а не всю коллекцию

2019-01-08 08:46 UTC, iBublik commented on app/views/admin/gists/_gist.html.erb
> +    <td><%= link_to gist.question.body[0, 25], admin_question_path(gist.question) %></td>
В рельсах есть хелпер `truncate`, используй его

2019-01-08 08:46 UTC, iBublik commented on app/views/admin/gists/_gist.html.erb
> +    <td><%= link_to gist.url, gist.url %></td>
В качестве текста ссылки должен выводиться хеш гиста (это его текстовый идентификатор в конце url-а)

2019-01-08 08:46 UTC, iBublik commented on lib/clients/git_hub_client.rb
> +class GitHubClient
Получилась странная обертка поверх официального клиента. При этом ничего полезного она не делает - зачем тогда вообще нужна?

2019-01-12 05:31 UTC, AShalysh commented on app/views/admin/gists/_gist.html.erb
> +<% @gists.each do |gist| %>
у меня рендерит всю коллекцию http://localhost:3000/admin/gists

2019-01-12 20:46 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +    Gist.create!(url: result.html_url, user: current_user, question: @test_passage.current_question) if result.present?
Правильно проверять, что тебе в ответ пришли какие-то данные (html_url), только тогда вызов считается успешным

2019-01-12 20:46 UTC, iBublik commented on app/views/admin/gists/_gist.html.erb
> +<% @gists.each do |gist| %>
Ну я и говорю, что ты нарушила конвенцию. Да, код работает, но конвенции нужны, чтоб людям было проще и быстрее понимать суть кода - по названии паршла можно сразу понять, что он рендерит 1 запись.

2019-01-12 20:46 UTC, iBublik commented on app/views/admin/gists/_gist.html.erb
> +    <td><%= link_to gist.url.split('/')[-1], gist.url %></td>
Это стоит вынести в хелпер, чтоб по имени было понятно назначение

2019-01-16 04:21 UTC, merged