Associations
AShalysh/testguru pull request #4
Opened 2018-09-11 05:37 UTC by AShalysh

2018-09-11 15:44 UTC, iBublik requested changes
На уровне БД тест с автором никак не связан, что делает ассоциацию нерабочей

2018-09-11 15:44 UTC, iBublik commented on app/models/category.rb
> +  has_many :tests
При создании `has_many` связей следует указывать что делать с дочерними записями при удалении родителя (опция `dependent`)

2018-09-11 15:44 UTC, iBublik commented on app/models/test.rb
> +  belongs_to :user
Представь, что видишь код `test.users` и `test.user`. Сможешь сходу понять в чем их отличие и назначение?
Ассоциации нужно называть понятно, чтоб не глядя в код можно было разобраться что происходит

2018-09-11 15:44 UTC, iBublik commented on app/models/user.rb
> +  has_many :tests
Ты переопределила ассоциацию, объявленную строкой выше

2018-09-12 09:05 UTC, AShalysh commented on app/models/test.rb
> +  belongs_to :user
test.users otnositsia k pol'zovateliam, a test.user - avtor
Ia dopolnila vot eto: alias_attribute :user, :author

2018-09-13 08:58 UTC, iBublik commented on db/migrate/20180912082932_add_user_to_tests.rb
> +    add_reference :tests, :user, foreign_key: true
На будущее - можно писать `add_reference :tests, :author, foreign_key: { to_table: :users }`. Тогда меньше опций при описании ассоциации придется указывать. Так же не забывай, что для полей-связей рекомендуется индекс создавать

2018-09-14 07:35 UTC, merged